name       : hatari
homepage   : https://hatari.tuxfamily.org/
version    : 2.1.0
release    : 8
source     :
    - https://download.tuxfamily.org/hatari/2.1.0/hatari-2.1.0.tar.bz2 : eb299460e92db4a8a2983a0725cbbc8c185f1470b8ecd791b3d102815da20924
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Hatari is an Atari ST/STE/TT/Falcon emulator
description: |
    Hatari is an Atari ST/STE/TT/Falcon emulator for GNU/Linux, BSD, Mac OS X, Windows and other systems which are supported by the SDL library.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
