name       : hatari
homepage   : https://hatari.tuxfamily.org/
version    : 2.0.0
release    : 5
source     :
    - https://download.tuxfamily.org/hatari/2.0.0/hatari-2.0.0.tar.bz2 : 52a447a59b6979d55d1525f3c4a21ec013e4371354d6683ede71546c5e6da577
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Hatari is an Atari ST/STE/TT/Falcon emulator
description: |
    Hatari is an Atari ST/STE/TT/Falcon emulator for GNU/Linux, BSD, Mac OS X, Windows and other systems which are supported by the SDL library.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
