name       : hatari
version    : 1.9.0
release    : 1
source     :
    - http://download.tuxfamily.org/hatari/1.9.0/hatari-1.9.0.tar.bz2 : b2b56e6cbe7f8769a5e8b1d96599f392d9351b44cacf959da6905da06d30e992
license    : GPL-2.0
summary    : Hatari is an Atari ST/STE/TT/Falcon emulator.
description: Hatari is an Atari ST/STE/TT/Falcon emulator for GNU/Linux, BSD, Mac OS X, Windows and other systems which are supported by the SDL library.
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig(libpng)
    - pkgconfig(portaudio-2.0)

setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
